import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import ClientCleanup from "./ClientCleanup"; // komponen client terpisah

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Swara",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.svg",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${lexend.variable} font-lexend antialiased`}>
        <ClientCleanup />
        {children}
      </body>

      <Script
        src="https://cdn.userway.org/widget.js"
        data-account="Kk9MFRMO7Y"
      />
    </html>
  );
}
